### ISSUE TITLE
Create a test case that ensures consolidation happens immediately after extracting the minimum from a root list with a single node

### ISSUE THREAD

**Issue by Tyriar** [gwtw/js-fibonacci-heap#10]
See https://github.com/gwtw/js-fibonacci-heap/pull/8#discussion_r85830994

**Comment by Tyriar** [comment]
@Alex777UAE I had a go trying to make a test case for this and I think the assumption that the lists are sorted is correct because of this line in `mergeLists` https://github.com/gwtw/js-fibonacci-heap/blob/0f52b831a61404b8927af710869df3e450dd0317/index.js#L352

This is the test case that always passed on an older version of the lib (7468d7d3f28065170ddfffc9f4251c25720efa2d)

``` js
test('should consolidate after extract min is called on a tree with a single tree in the root node list', function (t) {
  var heap = new Heap();
  var node0 = heap.insert(0, null);
  var node1 = heap.insert(1, null);
  var node2 = heap.insert(2, null); // I tried moving this line around
  heap.insert(6, null);
  heap.insert(7, null);
  heap.insert(3, null);
  heap.insert(4, null);
  heap.insert(5, null);
  heap.insert(8, null);

  // Extract minimum to trigger a consolidate
  t.is(heap.extractMinimum(), node0);

  // Extract minimum to ensure the extracted minimum node's children are being consolidated
  t.is(heap.extractMinimum(), node1);
  t.true(heap.findMinimum() === node2);
});
```

**Comment by Alex777UAE** [comment]
You compare only 2 nodes, and after that you still don't have fully ordered list.

Question should be asked, how can I guarantee that parent.child is always pointing to smallest node of the list?

**Comment by Alex777UAE** [comment]
Even if initially you order everything somehow, after cutting/deleting/decreasing some random key you don't have any idea which is smallest in the list.

**Comment by Tyriar** [comment]
Thanks heaps @Alex777UAE! I managed to put a test together that fails before and passes after your fix.

**Comment by Tyriar** [comment]
I added the other test case, bumped the version to 1.0.9 and published :fireworks:

**Comment by Alex777UAE** [comment]
Well done! Congrats!
